apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "endpoints", "nodes", "pods", "services", "namespaces", "events", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]  # Added rule for apiextensions.k8s.io group (unchanged)
  resources: ["customresourcedefinitions"]  # Limit access to customresourcedefinitions (unchanged)
  verbs: ["get", "list"]  # Grant only get and list verbs (unchanged)
# Added rules for networking.k8s.io and discovery.k8s.io API groups
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses", "endpointslices"]  # Resources required by Ingress controller
  verbs: ["get", "list", "watch"]  # Grant get, list, and watch verbs
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]  # Resource required for service discovery
  verbs: ["get", "list", "watch"]  # Grant get, list, and watch verbs
